### ISSUE TITLE
Error after upgrading from 0.61.5 to 0.62.0: Declaration of 'YGValue must be imported from module 'yoga' before it is required

### ISSUE THREAD

**Issue by Billydubb** [react-native-community/upgrade-support#20] opened 2020-03-29 07:47 UTC
## Environment
System:
    OS: macOS 10.15.3
    CPU: (8) x64 Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz
    Memory: 379.39 MB / 16.00 GB
    Shell: 5.0.11 - /usr/local/bin/bash
  Binaries:
    Node: 13.8.0 - /usr/local/bin/node
    Yarn: 1.22.0 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: 4.7.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 23, 25, 26, 27, 28
      Build Tools: 23.0.1, 25.0.0, 25.0.1, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 26.0.3, 27.0.2, 27.0.3, 28.0.3
      System Images: android-25 | Google APIs Intel x86 Atom, android-25 | Google APIs Intel x86 Atom_64, android-25 | Google Play Intel x86 Atom, android-26 | Google APIs Intel x86 Atom, android-26 | Google APIs Intel x86 Atom_64, android-26 | Google Play Intel x86 Atom, android-27 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom
      Android NDK: 17.1.4828580
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6241897
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  Languages:
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0
    react-native: 0.62.0 => 0.62.0
  npmGlobalPackages:
    *react-native*: Not Found

## Upgrading version

0.62.0

## Description

After following all the steps in the React Native Upgrade Helper(https://react-native-community.github.io/upgrade-helper/?from=0.61.5&to=0.62.0) to upgrade my app from version 0.61.5 to version 0.62.5, building the app on iOS fails with the following error message:

> Declaration of 'YGValue must be imported from module 'yoga' before it is required

<img width="209" alt="Screen Shot 2020-03-29 at 14 39 02" src="https://user-images.githubusercontent.com/1459741/77843914-ddb2be00-71cb-11ea-897e-90a3b961c4db.png">

## Reproducible demo

Follow the instructions to update from React Native Upgrade Helper(https://react-native-community.github.io/upgrade-helper/?from=0.61.5&to=0.62.0) from version 0.61.5 to version 0.62.0

**Comment by lucasbento** [comment] 2020-04-08 12:52
@Billydubb can you indicate which version of `CocoaPods` you are using?

**Comment by Billydubb** [comment] 2020-04-08 12:53
@lucasbento I am using version 1.5.3

**Comment by lucasbento** [comment] 2020-04-08 12:58
A shot in the dark but I noticed that the OP at facebook/react-native#28542 is also using that same version, can you try updating that to the latest (https://github.com/CocoaPods/CocoaPods/releases/tag/1.9.1)?

**Comment by Billydubb** [comment] 2020-04-08 13:02
Will try once I have the chance and will report back.

**Comment by shukerullah** [comment] 2020-04-08 15:32
After updating cocoapods to `1.9.1v`, its working fine.

**Comment by lucasbento** [comment] 2020-04-08 17:04
Awesome, thanks for reporting @shukerullah!

**Comment by Billydubb** [comment] 2020-04-10 08:47
After upgrading Cocoapods, the error has disappeared.

**Comment by lucasbento** [comment] 2020-04-10 08:59
Awesome, @Billydubb!

@thymikee based on this I'm wondering if we should apply a minimum supported version to CocoaPods in the doctor command. /cc @alloy

**Comment by thymikee** [comment] 2020-04-10 09:02
Are we sure this is due to CocoaPods upgrade, and not e.g. cache eviction?

**Comment by lucasbento** [comment] 2020-04-10 09:05
Good question but I'm honestly not sure.

My guess went to CocoaPods as the OP at the other issue had the same problem with the init template which I could not reproduce locally.

**Comment by Billydubb** [comment] 2020-04-10 09:09
@thymikee I nuked the entire pods folder, deleted the pods lockfile and did pod deintegrate several times. (also did the whole node modules purge, watchman-del-all and deleted all build folders) and it still didn't work

**Comment by thymikee** [comment] 2020-04-10 09:23
@Billydubb thanks. Anyway, I'm good with 1.9+ being a recommended version by `doctor` because it comes with default install speedups :)

**Comment by lucasbento** [comment] 2020-04-14 08:31
Closing this as it's resolved.

Created react-native-community/cli#1112 to implement CocoaPods version check in doctor.

Thanks @Billydubb!

**Closed by lucasbento** 2020-04-14 08:31 UTC
Labels: 0.62.0, ❔Question
